resources:
- ../../base/vote
- ../../base/result
- ../../base/worker
- ../../base/frontend
- ../../base/redis
- ../../base/db


commonLabels:
  environment: uat

patches:
- path: patch-result.yaml
- path: patch-worker.yaml

