resources:
- ../../base/vote
- ../../base/result
- ../../base/worker
- ../../base/frontend
- ../../base/redis
- ../../base/db


commonLabels:
  environment: uat

secretGenerator:
- name: db-secret
  type: Opaque
  literals:
  - password=postgres # Default for uat

