apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "/voting/db_password"
        objectType: "ssmparameter"
  secretObjects:
    - secretName: db-secret
      type: Opaque
      data:
        - objectName: "/voting/db_password"
          key: password