resources:
- ../../base/vote
- ../../base/result
- ../../base/worker
- ../../base/frontend
- ../../base/redis
- ../../base/db

commonLabels:
  environment: prod

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configurations:
- ../../kustomizeconfig.yaml

images:
- name: frontend
  newName: 563571752566.dkr.ecr.us-east-1.amazonaws.com/voting-app-frontend
  newTag: sha-16f590c
- name: result
  newName: 563571752566.dkr.ecr.us-east-1.amazonaws.com/voting-app-result
  newTag: sha-16f590c
- name: vote
  newName: 563571752566.dkr.ecr.us-east-1.amazonaws.com/voting-app-vote
  newTag: sha-16f590c
- name: worker
  newName: 563571752566.dkr.ecr.us-east-1.amazonaws.com/voting-app-worker
  newTag: sha-16f590c

patches:
- patch: |-
    - op: add
      path: /spec/template/metadata/labels/environment
      value: prod
  target:
    kind: Rollout
    name: vote
