resources:
- ../../base/vote
- ../../base/result
- ../../base/worker
- ../../base/frontend
- ../../base/redis
- ../../base/db

namePrefix: prod-
commonLabels:
  environment: prod

patches:
- path: patch-csi.yaml

