apiVersion: apps/v1
kind: Deployment
metadata:
  name: result
spec:
  template:
    spec:
      volumes:
      - name: secrets-store-inline
        csi:
          volumeAttributes:
            secretProviderClass: "prod-aws-secrets"