resources:
- ../../base/vote
- ../../base/result
- ../../base/worker
- ../../base/frontend
- ../../base/redis
- ../../base/db

namePrefix: dev-
commonLabels:
  environment: dev

patches:
- path: patch-csi.yaml
