resources:
- ../../base/vote
- ../../base/result
- ../../base/worker
- ../../base/frontend
- ../../base/redis
- ../../base/db


commonLabels:
  environment: dev

secretGenerator:
- literals:
  - password=postgres
  name: db-secret
  type: Opaque
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: frontend
  newName: 563571752566.dkr.ecr.us-east-1.amazonaws.com/voting-app-frontend
  newTag: sha-b434552
- name: result
  newName: 563571752566.dkr.ecr.us-east-1.amazonaws.com/voting-app-result
  newTag: sha-b434552
- name: vote
  newName: 563571752566.dkr.ecr.us-east-1.amazonaws.com/voting-app-vote
  newTag: sha-b434552
- name: worker
  newName: 563571752566.dkr.ecr.us-east-1.amazonaws.com/voting-app-worker
  newTag: sha-b434552

configurations:
- ../../kustomizeconfig.yaml
