apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  template:
    spec:
      volumes:
      - name: secrets-store-inline
        csi:
          volumeAttributes:
            secretProviderClass: "aws-secrets"