apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-result
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      labels:
        app: result
    spec:
      containers:
      - name: result
        image: "{{ .Values.image.registry }}/voting-app-result:{{ .Values.image.tag }}"
        env:
        - name: DB_PASSWORD
          value: {{ .Values.database.password | quote }}
        - name: PGSSLMODE
          value: "require"
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /api/health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /api/health
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: result
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: result
