apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/davidhsiaotw/voting-infra.git
    targetRevision: HEAD
    path: k8s-specifications/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app-uat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/davidhsiaotw/voting-infra.git
    targetRevision: HEAD
    path: k8s-specifications/overlays/uat
  destination:
    server: https://kubernetes.default.svc
    namespace: uat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/davidhsiaotw/voting-infra.git
    targetRevision: HEAD
    path: k8s-specifications/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
