name: Manual Deployment (CD)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'ECR Image Tag to deploy (e.g., v1.0.0, sha-xxxxxxx)'
        required: true
        default: 'latest'
      environment:
        description: 'Target Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - uat
          - prod

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: voting-cluster
  ECR_REGISTRY: 563571752566.dkr.ecr.us-east-1.amazonaws.com
  RDS_ENDPOINT: voting-app-db.clvdamp9sol9.us-east-1.rds.amazonaws.com
  CERT_ARN: arn:aws:acm:us-east-1:563571752566:certificate/ae459a1e-6875-4169-a7e3-42ce517665c2

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Infra Repo
        uses: actions/checkout@v5.0.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Install Helm
        uses: azure/setup-helm@v5.0.0

      - name: Deploy with Helm
        run: |
          # Fetch the DB Password from SSM
          DB_PASS=$(aws ssm get-parameter --name "/voting/db_password" --with-decryption --query "Parameter.Value" --output text)

          # Use the environment name in the release name to allow side-by-side installs
          helm upgrade --install voting-app-${{ github.event.inputs.environment }} ./charts/voting-app \
            --namespace ${{ github.event.inputs.environment }} \
            --create-namespace \
            --set image.registry=${{ env.ECR_REGISTRY }} \
            --set image.tag=${{ github.event.inputs.tag }} \
            --set database.endpoint=${{ env.RDS_ENDPOINT }} \
            --set database.password=$DB_PASS \
            --set frontend.sslCertArn=${{ env.CERT_ARN }}
