name: Manual Deployment (CD)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'ECR Image Tag to deploy (e.g., v1.0.0, sha-xxxxxxx)'
        required: true
        default: 'latest'
      environment:
        description: 'Target Environment'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - uat
          - prod
  repository_dispatch:
    types: [deploy-event]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      CLUSTER_NAME: ${{ vars.CLUSTER_NAME }}
      ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}
      RDS_ENDPOINT: ${{ vars.RDS_ENDPOINT }}
      CERT_ARN: ${{ vars.CERT_ARN }}
    steps:
      - name: Determine Deployment Variables
        id: vars
        run: |
          if [ "${{ github.event_name }}" == "repository_dispatch" ]; then
            echo "DEPLOY_TAG=${{ github.event.client_payload.tag }}" >> $GITHUB_OUTPUT
            echo "DEPLOY_ENV=${{ github.event.client_payload.environment }}" >> $GITHUB_OUTPUT
          else
            echo "DEPLOY_TAG=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
            echo "DEPLOY_ENV=${{ github.event.inputs.environment }}" >> $GITHUB_OUTPUT
          fi

      - name: Checkout Infra Repo
        uses: actions/checkout@v5.0.1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Install Helm
        uses: azure/setup-helm@v5.0.0

      - name: Deploy with Helm
        run: |
          # Fetch the DB Password from SSM
          DB_PASS=$(aws ssm get-parameter --name "/voting/db_password" --with-decryption --query "Parameter.Value" --output text)

          # Use the environment name in the release name to allow side-by-side installs
          helm upgrade --install voting-app-${{ steps.vars.outputs.DEPLOY_ENV }} ./charts/voting-app \
            --namespace ${{ steps.vars.outputs.DEPLOY_ENV }} \
            --create-namespace \
            --set image.registry=${{ env.ECR_REGISTRY }} \
            --set image.tag=${{ steps.vars.outputs.DEPLOY_TAG }} \
            --set database.endpoint=${{ env.RDS_ENDPOINT }} \
            --set database.password=$DB_PASS \
            --set frontend.sslCertArn=${{ env.CERT_ARN }}
