name: Manual Teardown (CD)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment to Delete'
        required: true
        default: 'uat'
        type: choice
        options:
          - dev
          - uat

env:
  AWS_REGION: us-east-1
  CLUSTER_NAME: voting-cluster

jobs:
  teardown:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Update Kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}

      - name: Install Helm
        uses: azure/setup-helm@v5.0.0

      - name: Uninstall Helm Release and Delete Namespace
        run: |
          helm uninstall voting-app-${{ github.event.inputs.environment }} --namespace ${{ github.event.inputs.environment }} || true
          kubectl delete namespace ${{ github.event.inputs.environment }} || true