apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: prod
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  backoffLimit: 2
  template:
    spec:
      containers:
      - name: flyway
        image: 471318789453.dkr.ecr.us-east-1.amazonaws.com/voting-app-schema:prod-v0.0.2
        command:
        - sh
        - -c
        - "flyway -url=jdbc:postgresql://$DB_ENDPOINT/postgres -user=postgres -password=$DB_PASSWORD migrate"
        envFrom:
        - secretRef:
            name: db-credentials
      restartPolicy: Never