apiVersion: v1
kind: ConfigMap
metadata:
  name: db-schema
  namespace: prod
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-weight: "-1"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
data:
  V1__Create_votes_table.sql: |
    CREATE TABLE IF NOT EXISTS votes (
      id VARCHAR(255) PRIMARY KEY,
      vote VARCHAR(255) NOT NULL
    );